const INTENTS = Object.freeze({
  NOOP: "NOOP",
  SCROLL: "SCROLL",
  SCROLL_TOP: "SCROLL_TOP",
  SCROLL_BOTTOM: "SCROLL_BOTTOM",
  PAGE_DOWN: "PAGE_DOWN",
  PAGE_UP: "PAGE_UP",
  NAV_BACK: "NAV_BACK",
  NAV_FORWARD: "NAV_FORWARD",
  RELOAD_PAGE: "RELOAD_PAGE",
  ENTER_INSERT: "ENTER_INSERT",
  ENTER_NORMAL: "ENTER_NORMAL",
  SHOW_COMMAND: "SHOW_COMMAND",
  HIDE_COMMAND: "HIDE_COMMAND",
  COMMAND_INPUT: "COMMAND_INPUT",
  SUBMIT_EDITOR_COMMAND: "SUBMIT_EDITOR_COMMAND",
  SHOW_WHICHKEY: "SHOW_WHICHKEY",
  UPDATE_WHICHKEY: "UPDATE_WHICHKEY",
  HIDE_WHICHKEY: "HIDE_WHICHKEY",
  OPEN_URL_PROMPT: "OPEN_URL_PROMPT",
  OPEN_URL: "OPEN_URL",
  SEARCH_WEB: "SEARCH_WEB",
  NEW_BUFFER: "NEW_BUFFER",
  BUFFER_NEXT: "BUFFER_NEXT",
  BUFFER_PREV: "BUFFER_PREV",
  SWITCH_BUFFER: "SWITCH_BUFFER",
  CLOSE_BUFFER: "CLOSE_BUFFER",
  CLOSE_FOCUSED: "CLOSE_FOCUSED",
  CLOSE_LEFT_BUFFERS: "CLOSE_LEFT_BUFFERS",
  CLOSE_RIGHT_BUFFERS: "CLOSE_RIGHT_BUFFERS",
  SPLIT_VERTICAL: "SPLIT_VERTICAL",
  SPLIT_CLOSE_RIGHT: "SPLIT_CLOSE_RIGHT",
  SPLIT_DEVTOOLS: "SPLIT_DEVTOOLS",
  FOCUS_SPLIT_LEFT: "FOCUS_SPLIT_LEFT",
  FOCUS_SPLIT_RIGHT: "FOCUS_SPLIT_RIGHT",
  CONFIG_RELOAD: "CONFIG_RELOAD",
  OPEN_SETTINGS_BUFFER: "OPEN_SETTINGS_BUFFER",
  TOGGLE_FOCUS_CONTEXT: "TOGGLE_FOCUS_CONTEXT",
  TOGGLE_URLLINE: "TOGGLE_URLLINE",
  SET_URLLINE_VISIBILITY: "SET_URLLINE_VISIBILITY",
  SET_THEME_MODE: "SET_THEME_MODE",
  SET_BROWSER_LANGUAGE: "SET_BROWSER_LANGUAGE",
  QUIT: "QUIT",
  UNKNOWN_COMMAND: "UNKNOWN_COMMAND",
});

const KNOWN_INTENTS = new Set(Object.values(INTENTS));

function isKnownIntentType(type) {
  return KNOWN_INTENTS.has(type);
}

module.exports = {
  INTENTS,
  KNOWN_INTENTS,
  isKnownIntentType,
};
